<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    public function run(): void
    {
        $banks = $this->listBank();
        foreach ($banks as $bank) {
            Bank::firstOrCreate(['code' => $bank['code']], [
                'name' => $bank['name'],
                'type' => $bank['type'],
            ]);
        }
    }

    private function listBank(): array
    {
        return [
            ['code' => 'ACEH', 'type' => 'Bank', 'name' => 'BPD Aceh'],
            ['code' => 'ACEH_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Aceh Syariah (UUS)'],
            ['code' => 'AGRONIAGA', 'type' => 'Bank', 'name' => 'Bank Raya Indonesia (sebelumnya bernama Bank BRI Agroniaga)'],
            ['code' => 'ALADIN', 'type' => 'Bank', 'name' => 'Bank Aladin Syariah (sebelumnya bernama Bank Maybank Syariah Indonesia)'],
            ['code' => 'ALLO', 'type' => 'Bank', 'name' => 'Allo Bank Indonesia (sebelumnya bernama Bank Harda Internasional)'],
            ['code' => 'AMAR', 'type' => 'Bank', 'name' => 'Bank Amar Indonesia (sebelumnya bernama Anglomas International Bank)'],
            ['code' => 'ANZ', 'type' => 'Bank', 'name' => 'Bank ANZ Indonesia'],
            ['code' => 'ARTHA', 'type' => 'Bank', 'name' => 'Bank Artha Graha International'],
            ['code' => 'BALI', 'type' => 'Bank', 'name' => 'BPD Bali'],
            ['code' => 'BAML', 'type' => 'Bank', 'name' => 'Bank of America Merill-Lynch'],
            ['code' => 'BANTEN', 'type' => 'Bank', 'name' => 'BPD Banten (sebelumnya bernama Bank Pundi Indonesia)'],
            ['code' => 'BCA', 'type' => 'Bank', 'name' => 'Bank Central Asia (BCA)'],
            ['code' => 'BCA_DIGITAL', 'type' => 'Bank', 'name' => 'Bank Central Asia Digital (BluBCA)'],
            ['code' => 'BCA_SYR', 'type' => 'Bank', 'name' => 'Bank Central Asia (BCA) Syariah'],
            ['code' => 'BENGKULU', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Bengkulu'],
            ['code' => 'BISNIS_INTERNASIONAL', 'type' => 'Bank', 'name' => 'Bank Bisnis Internasional'],
            ['code' => 'BJB', 'type' => 'Bank', 'name' => 'Bank BJB'],
            ['code' => 'BJB_SYR', 'type' => 'Bank', 'name' => 'Bank BJB Syariah'],
            ['code' => 'BNC', 'type' => 'Bank', 'name' => 'Bank Neo Commerce (sebelumnya bernama Bank Yudha Bhakti)'],
            ['code' => 'BNI', 'type' => 'Bank', 'name' => 'Bank Negara Indonesia (BNI)'],
            ['code' => 'BNP_PARIBAS', 'type' => 'Bank', 'name' => 'Bank BNP Paribas'],
            ['code' => 'BOC', 'type' => 'Bank', 'name' => 'Bank of China (BOC)'],
            ['code' => 'BRI', 'type' => 'Bank', 'name' => 'Bank Rakyat Indonesia (BRI)'],
            ['code' => 'BSI', 'type' => 'Bank', 'name' => 'Bank Syariah Indonesia (BSI)'],
            ['code' => 'BTN', 'type' => 'Bank', 'name' => 'Bank Tabungan Negara (BTN)'],
            ['code' => 'BTN_UUS', 'type' => 'Bank', 'name' => 'Bank Tabungan Negara Syariah (BTN UUS)'],
            ['code' => 'BTPN_SYARIAH', 'type' => 'Bank', 'name' => 'BTPN Syariah (sebelumnya bernama BTPN UUS (Syariah) and Bank Sahabat Purba Danarta)'],
            ['code' => 'BUKOPIN', 'type' => 'Bank', 'name' => 'Bank Bukopin'],
            ['code' => 'BUKOPIN_SYR', 'type' => 'Bank', 'name' => 'Bank Syariah Bukopin'],
            ['code' => 'BUMI_ARTA', 'type' => 'Bank', 'name' => 'Bank Bumi Arta'],
            ['code' => 'CAPITAL', 'type' => 'Bank', 'name' => 'Bank Capital Indonesia'],
            ['code' => 'CCB', 'type' => 'Bank', 'name' => 'China Construction Bank Indonesia (sebelumnya bernama Bank Antar Daerah dan Bank Windu Kentjana International)'],
            ['code' => 'CHINATRUST', 'type' => 'Bank', 'name' => 'Bank Chinatrust Indonesia'],
            ['code' => 'CIMB', 'type' => 'Bank', 'name' => 'Bank CIMB Niaga'],
            ['code' => 'CIMB_UUS', 'type' => 'Bank', 'name' => 'Bank CIMB Niaga Syariah (UUS)'],
            ['code' => 'CITIBANK', 'type' => 'Bank', 'name' => 'Citibank'],
            ['code' => 'COMMONWEALTH', 'type' => 'Bank', 'name' => 'Bank Commonwealth'],
            ['code' => 'DAERAH_ISTIMEWA', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Daerah Istimewa Yogyakarta (DIY)'],
            ['code' => 'DAERAH_ISTIMEWA_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Daerah Istimewa Yogyakarta Syariah (DIY UUS)'],
            ['code' => 'DANAMON', 'type' => 'Bank', 'name' => 'Bank Danamon'],
            ['code' => 'DANAMON_UUS', 'type' => 'Bank', 'name' => 'Bank Danamon Syariah (UUS)'],
            ['code' => 'DBS', 'type' => 'Bank', 'name' => 'Bank DBS Indonesia'],
            ['code' => 'DEUTSCHE', 'type' => 'Bank', 'name' => 'Deutsche Bank'],
            ['code' => 'DKI', 'type' => 'Bank', 'name' => 'Bank DKI'],
            ['code' => 'DKI_UUS', 'type' => 'Bank', 'name' => 'Bank DKI Syariah (UUS)'],
            ['code' => 'FAMA', 'type' => 'Bank', 'name' => 'Bank Fama International'],
            ['code' => 'GANESHA', 'type' => 'Bank', 'name' => 'Bank Ganesha'],
            ['code' => 'HANA', 'type' => 'Bank', 'name' => 'Bank Hana'],
            ['code' => 'HSBC', 'type' => 'Bank', 'name' => 'HSBC Indonesia (sebelumnya bernama Bank Ekonomi Raharja)'],
            ['code' => 'HSBC_UUS', 'type' => 'Bank', 'name' => 'Hongkong and Shanghai Bank Corporation Syariah (HSBC UUS)'],
            ['code' => 'IBK', 'type' => 'Bank', 'name' => 'Bank IBK Indonesia (sebelumnya bernama Bank Agris)'],
            ['code' => 'ICBC', 'type' => 'Bank', 'name' => 'Bank ICBC Indonesia'],
            ['code' => 'INA_PERDANA', 'type' => 'Bank', 'name' => 'Bank Ina Perdania'],
            ['code' => 'INDEX_SELINDO', 'type' => 'Bank', 'name' => 'Bank Index Selindo'],
            ['code' => 'INDIA', 'type' => 'Bank', 'name' => 'Bank of India Indonesia'],
            ['code' => 'JAGO', 'type' => 'Bank', 'name' => 'Bank Jago (sebelumnya bernama Bank Artos Indonesia)'],
            ['code' => 'JAMBI', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Jambi'],
            ['code' => 'JAMBI_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Jambi Syariah (UUS)'],
            ['code' => 'JASA_JAKARTA', 'type' => 'Bank', 'name' => 'Bank Jasa Jakarta'],
            ['code' => 'JAWA_TENGAH', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Jawa Tengah'],
            ['code' => 'JAWA_TENGAH_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Jawa Tengah Syariah (UUS)'],
            ['code' => 'JAWA_TIMUR', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Jawa Timur'],
            ['code' => 'JAWA_TIMUR_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Jawa Timur Syariah (UUS)'],
            ['code' => 'JPMORGAN', 'type' => 'Bank', 'name' => 'JP Morgan Chase Bank'],
            ['code' => 'JTRUST', 'type' => 'Bank', 'name' => 'Bank JTrust Indonesia (sebelumnya bernama Bank Mutiara)'],
            ['code' => 'KALIMANTAN_BARAT', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Kalimantan Barat'],
            ['code' => 'KALIMANTAN_BARAT_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Kalimantan Barat Syariah (UUS)'],
            ['code' => 'KALIMANTAN_SELATAN', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Kalimantan Selatan'],
            ['code' => 'KALIMANTAN_SELATAN_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Kalimantan Selatan Syariah (UUS)'],
            ['code' => 'KALIMANTAN_TENGAH', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Kalimantan Tengah'],
            ['code' => 'KALIMANTAN_TIMUR', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Kalimantan Timur'],
            ['code' => 'KALIMANTAN_TIMUR_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Kalimantan Timur Syariah (UUS)'],
            ['code' => 'LAMPUNG', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Lampung'],
            ['code' => 'MALUKU', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Maluku'],
            ['code' => 'MANDIRI', 'type' => 'Bank', 'name' => 'Bank Mandiri'],
            ['code' => 'MANDIRI_TASPEN', 'type' => 'Bank', 'name' => 'Mandiri Taspen Pos (sebelumnya bernama Bank Sinar Harapan Bali)'],
            ['code' => 'MASPION', 'type' => 'Bank', 'name' => 'Bank Maspion Indonesia'],
            ['code' => 'MAYAPADA', 'type' => 'Bank', 'name' => 'Bank Mayapada International'],
            ['code' => 'MAYBANK', 'type' => 'Bank', 'name' => 'Bank Maybank'],
            ['code' => 'MAYORA', 'type' => 'Bank', 'name' => 'Bank Mayora'],
            ['code' => 'MEGA', 'type' => 'Bank', 'name' => 'Bank Mega'],
            ['code' => 'MEGA_SYR', 'type' => 'Bank', 'name' => 'Bank Syariah Mega'],
            ['code' => 'MESTIKA_DHARMA', 'type' => 'Bank', 'name' => 'Bank Mestika Dharma'],
            ['code' => 'MIZUHO', 'type' => 'Bank', 'name' => 'Bank Mizuho Indonesia'],
            ['code' => 'MNC_INTERNASIONAL', 'type' => 'Bank', 'name' => 'Bank MNC Internasional'],
            ['code' => 'MUAMALAT', 'type' => 'Bank', 'name' => 'Bank Muamalat Indonesia'],
            ['code' => 'MULTI_ARTA_SENTOSA', 'type' => 'Bank', 'name' => 'Bank Multi Arta Sentosa'],
            ['code' => 'NATIONALNOBU', 'type' => 'Bank', 'name' => 'Bank Nationalnobu'],
            ['code' => 'NUSA_TENGGARA_BARAT', 'type' => 'Bank', 'name' => 'BPD Nusa Tenggara Barat'],
            ['code' => 'NUSA_TENGGARA_TIMUR', 'type' => 'Bank', 'name' => 'BPD Nusa Tenggara Timur'],
            ['code' => 'OCBC', 'type' => 'Bank', 'name' => 'Bank OCBC NISP'],
            ['code' => 'OCBC_UUS', 'type' => 'Bank', 'name' => 'Bank OCBC NISP Syariah (UUS)'],
            ['code' => 'OKE', 'type' => 'Bank', 'name' => 'Bank Oke Indonesia (sebelumnya bernama Bank Andara)'],
            ['code' => 'PANIN', 'type' => 'Bank', 'name' => 'Bank Panin'],
            ['code' => 'PANIN_SYR', 'type' => 'Bank', 'name' => 'Bank Panin Syariah'],
            ['code' => 'PAPUA', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Papua'],
            ['code' => 'PERMATA', 'type' => 'Bank', 'name' => 'Bank Permata'],
            ['code' => 'PERMATA_UUS', 'type' => 'Bank', 'name' => 'Bank Permata Syariah (UUS)'],
            ['code' => 'PRIMA_MASTER', 'type' => 'Bank', 'name' => 'Prima Master Bank'],
            ['code' => 'QNB_INDONESIA', 'type' => 'Bank', 'name' => 'Bank QNB Indonesia (sebelumnya bernama Bank QNB Kesawan)'],
            ['code' => 'RABOBANK', 'type' => 'Bank', 'name' => 'Bank Rabobank International Indonesia'],
            ['code' => 'RESONA', 'type' => 'Bank', 'name' => 'Bank Resona Perdania'],
            ['code' => 'RIAU_DAN_KEPRI', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Riau Dan Kepri'],
            ['code' => 'SAHABAT_SAMPOERNA', 'type' => 'Bank', 'name' => 'Bank Sahabat Sampoerna'],
            ['code' => 'SBI_INDONESIA', 'type' => 'Bank', 'name' => 'Bank SBI Indonesia'],
            ['code' => 'SEABANK', 'type' => 'Bank', 'name' => 'Bank Seabank Indonesia (sebelumnya bernama Bank Kesejahteraan Ekonomi)'],
            ['code' => 'SHINHAN', 'type' => 'Bank', 'name' => 'Bank Shinhan Indonesia (sebelumnya bernama Bank Metro Express)'],
            ['code' => 'SINARMAS', 'type' => 'Bank', 'name' => 'Bank Sinarmas'],
            ['code' => 'SINARMAS_UUS', 'type' => 'Bank', 'name' => 'Bank Sinarmas Syariah (UUS)'],
            ['code' => 'STANDARD_CHARTERED', 'type' => 'Bank', 'name' => 'Standard Charted Bank'],
            ['code' => 'SULAWESI', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sulawesi Tengah'],
            ['code' => 'SULAWESI_TENGGARA', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sulawesi Tenggara'],
            ['code' => 'SULSELBAR', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sulselbar'],
            ['code' => 'SULSELBAR_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sulselbar Syariah (UUS)'],
            ['code' => 'SULUT', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sulut'],
            ['code' => 'SUMATERA_BARAT', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sumatera Barat'],
            ['code' => 'SUMATERA_BARAT_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sumatera Barat Syariah (UUS)'],
            ['code' => 'SUMSEL_DAN_BABEL', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sumsel Dan Babel'],
            ['code' => 'SUMSEL_DAN_BABEL_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sumsel Dan Babel Syariah (UUS)'],
            ['code' => 'SUMUT', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sumut'],
            ['code' => 'SUMUT_UUS', 'type' => 'Bank', 'name' => 'Bank Pembangunan Daerah Sumut Syariah (UUS)'],
            ['code' => 'TABUNGAN_PENSIUNAN_NASIONAL', 'type' => 'Bank', 'name' => 'Bank Tabungan Pensiunan Nasional (BTPN)'],
            ['code' => 'TOKYO', 'type' => 'Bank', 'name' => 'Bank of Tokyo Mitsubishi UFJ (MUFJ)'],
            ['code' => 'UOB', 'type' => 'Bank', 'name' => 'Bank UOB Indonesia'],
            ['code' => 'VICTORIA_INTERNASIONAL', 'type' => 'Bank', 'name' => 'Bank Victoria Internasional'],
            ['code' => 'VICTORIA_SYR', 'type' => 'Bank', 'name' => 'Bank Victoria Syariah'],
            ['code' => 'WOORI', 'type' => 'Bank', 'name' => 'Bank Woori Indonesia'],
        ];
    }
}
